### ISSUE TITLE
Redirect old feed urls to new blog

### ISSUE THREAD

**Issue by akoeplinger** [joeduffy/joeduffy.github.io#3]
I'm subscribed to the blog via feedly, which apparently uses http://www.bluebytesoftware.com/blog/SyndicationService.asmx/GetRss. This means the latest updates don't show up as that feed doesn't redirect to the new url.

**Comment by joeduffy** [comment]
I am working on this.  Thanks for letting me know.  A fix is somewhat complex and involves some DNS trickery however I should have it figured out in a day or two.

**Comment by akoeplinger** [comment]
Thanks Joe, no hurry I'm following you on twitter for the latest news anyway :smile:

**Comment by terrajobst** [comment]
:+1:

**Comment by joeduffy** [comment]
I've finally finished doing this.  Sadly I had lost my credentials for anything to do with bluebytesoftware.com, so it took longer than I anticipated.  Sorry.  Hope all is well now, though!
