### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by terrajobst** [joeduffy/joeduffy.github.io#4]
Are you interested in incorporating comments via, for instance, Disqus?

**Comment by joeduffy** [comment]
Absolutely.

No desire to be antisocial!

I looked at Disqus, however I've seen enough cases where it was clunky and/or misbehaved.  I also vaguely recall you need a Disqus account to comment which I assume most people don't have.

I'm considering some kind of GitHub based thing but unsure how best to do it.  Code reviews and issues are more actionable but don't integrate well with the content.  An opportunity for a nice tool here, I think, and may just build it over the holidays :-)

**Comment by WalkingCat** [comment]
Disqus has a 'guest commenting' option to avoid login.
https://help.disqus.com/customer/portal/articles/832187-guest-commenting
